// Code generated by "stringer -type CommandStatus"; DO NOT EDIT

package runss

import "fmt"

const _CommandStatus_name = "PendingInProgressCancellingSuccessTimedOutCancelledFailed"

var _CommandStatus_index = [...]uint8{0, 7, 17, 27, 34, 42, 51, 57}

func (i CommandStatus) String() string {
	if i < 0 || i >= CommandStatus(len(_CommandStatus_index)-1) {
		return fmt.Sprintf("CommandStatus(%d)", i)
	}
	return _CommandStatus_name[_CommandStatus_index[i]:_CommandStatus_index[i+1]]
}
